name: asi-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - pip
  - pip:
      - pre-commit
      - ruff
      - black
      - pytest
      - wandb
